export const ADD_SELECTED_PROMPT = 'ADD_SELECTED_PROMPT'
export const REMOVE_SELECTED_PROMPT = 'REMOVE_SELECTED_PROMPT'

export const DELETE_POST = 'DELETE_POST';
// export const TOGGLE_FORM = 'TOGGLE_FORM';
export const UPDATE_SCORE = 'UPDATE_SCORE';