export const ADD_SELECTED_PROMPT = 'ADD_SELECTED_PROMPT'
export const REMOVE_SELECTED_PROMPT = 'REMOVE_SELECTED_PROMPT'

export const TOGGLE_LOGIN_FORM = 'TOGGLE_LOGIN_FORM'

export const DELETE_POST = 'DELETE_POST';
export const UPDATE_SCORE = 'UPDATE_SCORE';